### ISSUE TITLE
Feature Request: Portrait render of Skin (2D)

### ISSUE THREAD

**Issue by NightlandDriver** [crafatar/crafatar#279]
Hey

is it possible to show a portrait of the skin (head & half of the body)?
And if not it would be nice if that is added including the skin overlay.

**Comment by jomo** [comment]
I don't think there is a large need for this, so it probably won't be implemented implemented server side.

But you can of simply cut off the image at the client side (e.g. using [`clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) with CSS):

![screenshot](https://user-images.githubusercontent.com/3585743/105069684-93643b80-5a82-11eb-9723-4e2e91edfcbe.png)

That should give you fairly good results, see [jsbin](http://jsbin.com/metujepiko/1/edit?css,output).

```css
img.crafatar.bust {
  clip-path: polygon(
    0 0,
    100% 0,
    100% 43.6%,
    20% 64.1%,
    0 59%
  );
}
```
